/* =====================================================
   india-places.js — states, union territories and major
   cities, used to (a) power searchable destination
   dropdowns everywhere, and (b) let a quote entered at
   STATE level (e.g. "ODISHA") automatically apply to any
   city typed in that state during billing.

   Not every village is listed — if a destination isn't
   here, you can still type it freehand; it just won't get
   automatic state-level rate fallback unless you add it
   below.
   ===================================================== */

const INDIA_STATES = [
  "ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHHATTISGARH",
  "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JHARKHAND", "KARNATAKA",
  "KERALA", "MADHYA PRADESH", "MAHARASHTRA", "MANIPUR", "MEGHALAYA", "MIZORAM",
  "NAGALAND", "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU",
  "TELANGANA", "TRIPURA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL",
  "ANDAMAN AND NICOBAR ISLANDS", "CHANDIGARH",
  "DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DELHI", "JAMMU AND KASHMIR",
  "LADAKH", "LAKSHADWEEP", "PUDUCHERRY",
];

// city -> state map (also doubles as the master city list)
const INDIA_CITY_STATE = {
  "VISAKHAPATNAM": "ANDHRA PRADESH", "VIJAYAWADA": "ANDHRA PRADESH", "GUNTUR": "ANDHRA PRADESH",
  "TIRUPATI": "ANDHRA PRADESH", "NELLORE": "ANDHRA PRADESH", "KURNOOL": "ANDHRA PRADESH",
  "ITANAGAR": "ARUNACHAL PRADESH",
  "GUWAHATI": "ASSAM", "DIBRUGARH": "ASSAM", "SILCHAR": "ASSAM", "JORHAT": "ASSAM",
  "PATNA": "BIHAR", "GAYA": "BIHAR", "BHAGALPUR": "BIHAR", "MUZAFFARPUR": "BIHAR", "DARBHANGA": "BIHAR",
  "RAIPUR": "CHHATTISGARH", "BHILAI": "CHHATTISGARH", "BILASPUR": "CHHATTISGARH", "DURG": "CHHATTISGARH",
  "PANAJI": "GOA", "MARGAO": "GOA", "VASCO DA GAMA": "GOA",
  "AHMEDABAD": "GUJARAT", "SURAT": "GUJARAT", "VADODARA": "GUJARAT", "RAJKOT": "GUJARAT",
  "BHAVNAGAR": "GUJARAT", "JAMNAGAR": "GUJARAT", "GANDHINAGAR": "GUJARAT",
  "GURUGRAM": "HARYANA", "GURGAON": "HARYANA", "FARIDABAD": "HARYANA", "PANIPAT": "HARYANA",
  "AMBALA": "HARYANA", "HISAR": "HARYANA", "ROHTAK": "HARYANA", "KARNAL": "HARYANA",
  "SHIMLA": "HIMACHAL PRADESH", "MANALI": "HIMACHAL PRADESH", "DHARAMSHALA": "HIMACHAL PRADESH",
  "RANCHI": "JHARKHAND", "JAMSHEDPUR": "JHARKHAND", "DHANBAD": "JHARKHAND", "BOKARO": "JHARKHAND", "HAZARIBAGH": "JHARKHAND",
  "BENGALURU": "KARNATAKA", "BANGALORE": "KARNATAKA", "MYSURU": "KARNATAKA", "MYSORE": "KARNATAKA",
  "MANGALURU": "KARNATAKA", "MANGALORE": "KARNATAKA", "HUBLI": "KARNATAKA", "BELAGAVI": "KARNATAKA",
  "KOCHI": "KERALA", "COCHIN": "KERALA", "THIRUVANANTHAPURAM": "KERALA", "KOZHIKODE": "KERALA",
  "KOLLAM": "KERALA", "THRISSUR": "KERALA", "KOTTAYAM": "KERALA",
  "BHOPAL": "MADHYA PRADESH", "INDORE": "MADHYA PRADESH", "JABALPUR": "MADHYA PRADESH",
  "GWALIOR": "MADHYA PRADESH", "UJJAIN": "MADHYA PRADESH",
  "MUMBAI": "MAHARASHTRA", "PUNE": "MAHARASHTRA", "NAGPUR": "MAHARASHTRA", "NASHIK": "MAHARASHTRA",
  "AURANGABAD": "MAHARASHTRA", "THANE": "MAHARASHTRA", "SOLAPUR": "MAHARASHTRA", "KOLHAPUR": "MAHARASHTRA",
  "IMPHAL": "MANIPUR",
  "SHILLONG": "MEGHALAYA",
  "AIZAWL": "MIZORAM",
  "KOHIMA": "NAGALAND", "DIMAPUR": "NAGALAND",
  "BHUBANESWAR": "ODISHA", "BHUBANESHWAR": "ODISHA", "CUTTACK": "ODISHA", "ROURKELA": "ODISHA",
  "BERHAMPUR": "ODISHA", "SAMBALPUR": "ODISHA", "PURI": "ODISHA", "JHARSUGUDA": "ODISHA",
  "BALASORE": "ODISHA", "BARIPADA": "ODISHA", "ANGUL": "ODISHA", "BALANGIR": "ODISHA",
  "AMRITSAR": "PUNJAB", "LUDHIANA": "PUNJAB", "JALANDHAR": "PUNJAB", "PATIALA": "PUNJAB", "MOHALI": "PUNJAB",
  "JAIPUR": "RAJASTHAN", "JODHPUR": "RAJASTHAN", "UDAIPUR": "RAJASTHAN", "KOTA": "RAJASTHAN",
  "AJMER": "RAJASTHAN", "BIKANER": "RAJASTHAN",
  "GANGTOK": "SIKKIM",
  "CHENNAI": "TAMIL NADU", "COIMBATORE": "TAMIL NADU", "MADURAI": "TAMIL NADU", "TIRUCHIRAPPALLI": "TAMIL NADU",
  "SALEM": "TAMIL NADU", "TIRUNELVELI": "TAMIL NADU", "ERODE": "TAMIL NADU", "VELLORE": "TAMIL NADU",
  "HYDERABAD": "TELANGANA", "WARANGAL": "TELANGANA", "NIZAMABAD": "TELANGANA", "KARIMNAGAR": "TELANGANA",
  "AGARTALA": "TRIPURA",
  "LUCKNOW": "UTTAR PRADESH", "KANPUR": "UTTAR PRADESH", "AGRA": "UTTAR PRADESH", "VARANASI": "UTTAR PRADESH",
  "NOIDA": "UTTAR PRADESH", "GHAZIABAD": "UTTAR PRADESH", "MEERUT": "UTTAR PRADESH", "ALLAHABAD": "UTTAR PRADESH",
  "PRAYAGRAJ": "UTTAR PRADESH", "BAREILLY": "UTTAR PRADESH", "ALIGARH": "UTTAR PRADESH", "GORAKHPUR": "UTTAR PRADESH",
  "DEHRADUN": "UTTARAKHAND", "HARIDWAR": "UTTARAKHAND", "RISHIKESH": "UTTARAKHAND", "NAINITAL": "UTTARAKHAND",
  "KOLKATA": "WEST BENGAL", "HOWRAH": "WEST BENGAL", "DURGAPUR": "WEST BENGAL", "ASANSOL": "WEST BENGAL",
  "SILIGURI": "WEST BENGAL",
  "PORT BLAIR": "ANDAMAN AND NICOBAR ISLANDS",
  "CHANDIGARH": "CHANDIGARH",
  "DAMAN": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DIU": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
  "NEW DELHI": "DELHI", "DELHI": "DELHI",
  "SRINAGAR": "JAMMU AND KASHMIR", "JAMMU": "JAMMU AND KASHMIR",
  "LEH": "LADAKH",
  "KAVARATTI": "LAKSHADWEEP",
  "PUDUCHERRY": "PUDUCHERRY", "PONDICHERRY": "PUDUCHERRY",
};

/** Returns the state for a given city name, or null if unknown. */
function stateForCity(cityName) {
  if (!cityName) return null;
  return INDIA_CITY_STATE[cityName.trim().toUpperCase()] || null;
}

/** Every selectable destination name (states + cities), for dropdowns. */
function allDestinationNames() {
  const set = new Set([...INDIA_STATES, ...Object.keys(INDIA_CITY_STATE)]);
  return [...set].sort();
}
